const actionTypes = {
  USER_LOGGED_IN: "USER_LOGGED_IN",
  ADD_ITEM: "ADD_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  FETCH_ITEMS_BEGIN: "FETCH_ITEMS_BEGIN",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FAILURE: "FETCH_ITEMS_FAILURE"
};

export default actionTypes;
